---
- name: Install Prequisites
  apt:
    name: "dbus"
    state: present

- name: Set Hostname
  hostname:
    name: "{{ hostname }}"

- name: Set Timezone
  timezone:
    name: Europe/Berlin

- name: Create Scripts Directory
  become_user: "{{ user }}"
  file:
    path: "{{ script_dir }}"
    state: directory
    recurse: yes
